import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/request";

// this rendered on client
export default function Home({results}) {

  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Navbar */}
      <Nav />

      {/* Result */}
      <Results results={results} />
    </div>
  );
}

// this rendered on server, before the home page actually renders
// context prop here is url
export async function getServerSideProps(context) {
  // because in the url, we have genre query
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  
  return {
    props: {
      results : request.results,
    }
  }
}
